// Componentes base del sistema de diseño (docs/09-sistema-de-diseno.md). Fuente de verdad para todo lo nuevo; la guía viva
// está en /diseno. Solo usan tokens por función (app/globals.css): funcionan igual en claro y en oscuro.
export { Alerta } from "./alerta";
export { Avatar } from "./avatar";
export { Aviso, type TonoAviso } from "./aviso";
export { Boton, BotonIcono, type JerarquiaBoton, type TamanoBoton } from "./boton";
export { BotonCantidad, Cantidad } from "./cantidad";
export { BarraAbonado, BloqueDeuda, FechaDeuda, MontoDeuda } from "./bloque-deuda";
export { Buscador, Campo, CampoMonto, CampoMultilinea, soloDigitos } from "./campo";
export { CheckSeleccion } from "./check-seleccion";
export { ControlSegmentado } from "./control-segmentado";
export { Contador, Etiqueta, type TonoEtiqueta } from "./etiqueta";
export { FilaAgregar } from "./fila-agregar";
export { FilaLista, ListaAgrupada } from "./lista";
export { GrupoOpciones, Opcion } from "./opcion";
export { FilaPastillas, type OpcionFiltro } from "./pastilla";
export { TarjetaDocumento } from "./tarjeta-documento";
export { Tarjeta, type TonoTarjeta } from "./tarjeta";
export { ProveedorToast, useToastUI, VistaToast, type OpcionesToast } from "./toast";
export { VistaPreviaWhatsApp } from "./vista-previa-whatsapp";
export { ResumenDona, type CuadroResumen, type FilaResumen } from "./resumen-dona";
export { MallaViva, MazoJugadas, TarjetaJugada, type CartaJugada } from "./tarjeta-jugada";
export { CuadriculaSeleccion, type ElementoCuadricula } from "./cuadricula-seleccion";
export { ElegirMensaje, type MensajeElegible } from "./elegir-mensaje";
export { HojaProximamente, TarjetaProximamente } from "./funcion-en-preparacion";
export { Interruptor } from "./interruptor";
export { EditorEtiquetas } from "./editor-etiquetas";
export { TiraMedios, duracionCorta, type ElementoTira } from "./tira-medios";
export { FilaVariante } from "./fila-variante";
export { VideoProducto } from "./video-producto";
