// Emojis curados para el avatar de un cliente (no la lista Unicode completa): lo que usa una vendedora dominicana (belleza, moda, perfumes,
// joyas, hogar, comida, 🇩🇴, 🔥, 💅, 👑, 💎, 🌸…). Datos estáticos; el selector pinta una categoría a la vez.

export type EmojiAvatar = { e: string; n: string };
export type CategoriaEmoji = { id: string; nombre: string; icono: string; /** Sus emojis aceptan tono de piel. */ conTono: boolean; emojis: EmojiAvatar[] };

export const CATEGORIAS_EMOJI: CategoriaEmoji[] = [
  {
    id: "caras",
    nombre: "Caras",
    icono: "😀",
    conTono: false,
    emojis: [
      { e: "😀", n: "Sonriendo" }, { e: "😃", n: "Muy feliz" }, { e: "😄", n: "Feliz" }, { e: "😁", n: "Dientes" },
      { e: "😆", n: "Carcajada" }, { e: "😅", n: "Sudor de alivio" }, { e: "😂", n: "Llorando de risa" }, { e: "🤣", n: "Rodando de risa" },
      { e: "😊", n: "Sonrojada" }, { e: "😇", n: "Angelito" }, { e: "🙂", n: "Sonrisa suave" }, { e: "🙃", n: "Al revés" },
      { e: "😉", n: "Guiño" }, { e: "😍", n: "Ojos de corazón" }, { e: "🥰", n: "Enamorada" }, { e: "😘", n: "Beso" },
      { e: "😋", n: "Rico" }, { e: "😜", n: "Lengua y guiño" }, { e: "🤪", n: "Loquita" }, { e: "😎", n: "Con lentes" },
      { e: "🤩", n: "Ojos de estrella" }, { e: "🥳", n: "De fiesta" }, { e: "😏", n: "Pícara" }, { e: "🥺", n: "Carita suplicante" },
      { e: "😭", n: "Llorando" }, { e: "😤", n: "Resoplando" }, { e: "😡", n: "Furiosa" }, { e: "🤯", n: "Mente explotando" },
      { e: "😱", n: "Asustada" }, { e: "🤔", n: "Pensando" }, { e: "🤭", n: "Tapándose la boca" }, { e: "🤗", n: "Abrazo" },
      { e: "😴", n: "Durmiendo" }, { e: "🤑", n: "Con dinero" }, { e: "😌", n: "Aliviada" }, { e: "🥹", n: "Conmovida" },
    ],
  },
  {
    id: "personas",
    nombre: "Personas",
    icono: "👩",
    conTono: true,
    emojis: [
      { e: "👩", n: "Mujer" }, { e: "👨", n: "Hombre" }, { e: "🧑", n: "Persona" }, { e: "👧", n: "Niña" },
      { e: "👦", n: "Niño" }, { e: "👶", n: "Bebé" }, { e: "👵", n: "Abuela" }, { e: "👴", n: "Abuelo" },
      { e: "🧔", n: "Con barba" }, { e: "👱‍♀️", n: "Rubia" }, { e: "👩‍🦱", n: "Pelo rizado" }, { e: "👩‍🦰", n: "Pelirroja" },
      { e: "👩‍🦳", n: "Canosa" }, { e: "💅", n: "Uñas" }, { e: "💁‍♀️", n: "Con gesto" }, { e: "🙋‍♀️", n: "Mano arriba" },
      { e: "🙆‍♀️", n: "Brazos en alto" }, { e: "🤷‍♀️", n: "Ni idea" }, { e: "🙌", n: "Manos arriba" }, { e: "👏", n: "Aplausos" },
      { e: "🙏", n: "Gracias" }, { e: "💪", n: "Fuerza" }, { e: "👍", n: "Pulgar arriba" }, { e: "👌", n: "Perfecto" },
      { e: "✌️", n: "Paz" }, { e: "🤞", n: "Dedos cruzados" }, { e: "🤙", n: "Llámame" }, { e: "👋", n: "Saludo" },
      { e: "🤝", n: "Trato hecho" }, { e: "💃", n: "Bailarina" }, { e: "🕺", n: "Bailarín" }, { e: "👸", n: "Princesa" },
      { e: "🤴", n: "Príncipe" }, { e: "💇‍♀️", n: "Corte de pelo" }, { e: "💆‍♀️", n: "Masaje" }, { e: "🧖‍♀️", n: "Spa" },
    ],
  },
  {
    id: "moda",
    nombre: "Moda y ropa",
    icono: "👗",
    conTono: false,
    emojis: [
      { e: "👗", n: "Vestido" }, { e: "👚", n: "Blusa" }, { e: "👕", n: "Camiseta" }, { e: "👖", n: "Jeans" },
      { e: "🧥", n: "Chaqueta" }, { e: "👔", n: "Camisa" }, { e: "👙", n: "Bikini" }, { e: "👘", n: "Kimono" },
      { e: "🥻", n: "Sari" }, { e: "👠", n: "Tacón" }, { e: "👡", n: "Sandalia" }, { e: "👢", n: "Bota" },
      { e: "👟", n: "Tenis" }, { e: "🥿", n: "Zapato plano" }, { e: "👜", n: "Cartera" }, { e: "👛", n: "Monedero" },
      { e: "👝", n: "Bolsito" }, { e: "🎒", n: "Mochila" }, { e: "🕶️", n: "Lentes de sol" }, { e: "👓", n: "Lentes" },
      { e: "🧢", n: "Gorra" }, { e: "👒", n: "Sombrero" }, { e: "🎩", n: "Chistera" }, { e: "🧣", n: "Bufanda" },
      { e: "🧤", n: "Guantes" }, { e: "👑", n: "Corona" }, { e: "💍", n: "Anillo" }, { e: "📿", n: "Collar de cuentas" },
      { e: "🩱", n: "Traje de baño" }, { e: "🩴", n: "Chancleta" },
    ],
  },
  {
    id: "belleza",
    nombre: "Belleza y cuidado",
    icono: "💄",
    conTono: false,
    emojis: [
      { e: "💄", n: "Labial" }, { e: "🪞", n: "Espejo" }, { e: "🧴", n: "Crema" }, { e: "🧼", n: "Jabón" },
      { e: "🪮", n: "Peine" }, { e: "✂️", n: "Tijeras" }, { e: "🛁", n: "Bañera" }, { e: "🧽", n: "Esponja" },
      { e: "🪒", n: "Navaja" }, { e: "🌿", n: "Hierbas" }, { e: "🫧", n: "Burbujas" }, { e: "💎", n: "Diamante" },
      { e: "✨", n: "Brillos" }, { e: "🧪", n: "Esencias" }, { e: "🫙", n: "Frasco" }, { e: "🪥", n: "Cepillo de dientes" },
      { e: "🧖", n: "Mascarilla" }, { e: "🌹", n: "Rosa" }, { e: "🕯️", n: "Vela" }, { e: "🧿", n: "Amuleto" },
      { e: "🪬", n: "Hamsa" }, { e: "💧", n: "Gota" }, { e: "🍯", n: "Miel" }, { e: "🥥", n: "Coco" },
    ],
  },
  {
    id: "corazones",
    nombre: "Corazones y símbolos",
    icono: "💖",
    conTono: false,
    emojis: [
      { e: "❤️", n: "Corazón rojo" }, { e: "🧡", n: "Corazón naranja" }, { e: "💛", n: "Corazón amarillo" }, { e: "💚", n: "Corazón verde" },
      { e: "💙", n: "Corazón azul" }, { e: "💜", n: "Corazón morado" }, { e: "🖤", n: "Corazón negro" }, { e: "🤍", n: "Corazón blanco" },
      { e: "🤎", n: "Corazón café" }, { e: "💖", n: "Corazón brillante" }, { e: "💗", n: "Corazón creciendo" }, { e: "💓", n: "Corazón latiendo" },
      { e: "💞", n: "Corazones girando" }, { e: "💕", n: "Dos corazones" }, { e: "💘", n: "Flechazo" }, { e: "💝", n: "Corazón con lazo" },
      { e: "❤️‍🔥", n: "Corazón en llamas" }, { e: "⭐", n: "Estrella" }, { e: "🌟", n: "Estrella brillante" }, { e: "💫", n: "Mareo de estrellas" },
      { e: "🔥", n: "Fuego" }, { e: "💯", n: "Cien" }, { e: "✅", n: "Listo" }, { e: "❗", n: "Exclamación" },
      { e: "💥", n: "Explosión" }, { e: "🎶", n: "Música" }, { e: "♾️", n: "Infinito" }, { e: "🆕", n: "Nuevo" },
      { e: "🆒", n: "Cool" }, { e: "🔝", n: "Arriba" }, { e: "💲", n: "Dólar" }, { e: "🔱", n: "Tridente" },
    ],
  },
  {
    id: "animales",
    nombre: "Animales",
    icono: "🦋",
    conTono: false,
    emojis: [
      { e: "🐶", n: "Perro" }, { e: "🐱", n: "Gato" }, { e: "🐭", n: "Ratón" }, { e: "🐹", n: "Hámster" },
      { e: "🐰", n: "Conejo" }, { e: "🦊", n: "Zorro" }, { e: "🐻", n: "Oso" }, { e: "🐼", n: "Panda" },
      { e: "🐨", n: "Koala" }, { e: "🐯", n: "Tigre" }, { e: "🦁", n: "León" }, { e: "🐮", n: "Vaca" },
      { e: "🐷", n: "Cerdo" }, { e: "🐸", n: "Rana" }, { e: "🐵", n: "Mono" }, { e: "🐔", n: "Gallina" },
      { e: "🐧", n: "Pingüino" }, { e: "🐦", n: "Pájaro" }, { e: "🦄", n: "Unicornio" }, { e: "🐝", n: "Abeja" },
      { e: "🦋", n: "Mariposa" }, { e: "🐢", n: "Tortuga" }, { e: "🐬", n: "Delfín" }, { e: "🐠", n: "Pez" },
      { e: "🦜", n: "Loro" }, { e: "🦩", n: "Flamenco" }, { e: "🐞", n: "Mariquita" }, { e: "🦢", n: "Cisne" },
    ],
  },
  {
    id: "naturaleza",
    nombre: "Naturaleza y flores",
    icono: "🌸",
    conTono: false,
    emojis: [
      { e: "🌸", n: "Flor de cerezo" }, { e: "🌺", n: "Hibisco" }, { e: "🌹", n: "Rosa" }, { e: "🌷", n: "Tulipán" },
      { e: "🌻", n: "Girasol" }, { e: "🌼", n: "Margarita" }, { e: "💐", n: "Ramo" }, { e: "🪷", n: "Loto" },
      { e: "🌿", n: "Hierba" }, { e: "🍀", n: "Trébol" }, { e: "🌴", n: "Palmera" }, { e: "🌵", n: "Cactus" },
      { e: "🌳", n: "Árbol" }, { e: "🍃", n: "Hojas al viento" }, { e: "🍂", n: "Hojas secas" }, { e: "🌈", n: "Arcoíris" },
      { e: "☀️", n: "Sol" }, { e: "🌙", n: "Luna" }, { e: "☁️", n: "Nube" }, { e: "🌊", n: "Ola" },
      { e: "❄️", n: "Copo de nieve" }, { e: "🌎", n: "Tierra" }, { e: "🌕", n: "Luna llena" }, { e: "🌅", n: "Amanecer" },
      { e: "🌾", n: "Espigas" }, { e: "🐚", n: "Concha" }, { e: "🪻", n: "Lavanda" }, { e: "🪸", n: "Coral" },
    ],
  },
  {
    id: "comida",
    nombre: "Comida y bebida",
    icono: "🍓",
    conTono: false,
    emojis: [
      { e: "🍓", n: "Fresa" }, { e: "🍒", n: "Cerezas" }, { e: "🍑", n: "Durazno" }, { e: "🍎", n: "Manzana" },
      { e: "🍊", n: "Naranja" }, { e: "🍋", n: "Limón" }, { e: "🍌", n: "Plátano" }, { e: "🍍", n: "Piña" },
      { e: "🥭", n: "Mango" }, { e: "🍉", n: "Sandía" }, { e: "🍇", n: "Uvas" }, { e: "🥥", n: "Coco" },
      { e: "🍫", n: "Chocolate" }, { e: "🍰", n: "Pastel" }, { e: "🧁", n: "Cupcake" }, { e: "🍩", n: "Dona" },
      { e: "🍪", n: "Galleta" }, { e: "🍕", n: "Pizza" }, { e: "🍔", n: "Hamburguesa" }, { e: "🍟", n: "Papas fritas" },
      { e: "🍗", n: "Pollo" }, { e: "🍳", n: "Huevo frito" }, { e: "🥐", n: "Cruasán" }, { e: "🍞", n: "Pan" },
      { e: "🍷", n: "Vino" }, { e: "🍹", n: "Cóctel" }, { e: "🍺", n: "Cerveza" }, { e: "☕", n: "Café" },
      { e: "🧋", n: "Té de burbujas" }, { e: "🥤", n: "Refresco" }, { e: "🍦", n: "Helado" }, { e: "🥑", n: "Aguacate" },
    ],
  },
  {
    id: "fiestas",
    nombre: "Fiestas y regalos",
    icono: "🎁",
    conTono: false,
    emojis: [
      { e: "🎀", n: "Lazo" }, { e: "🎁", n: "Regalo" }, { e: "🎉", n: "Fiesta" }, { e: "🎊", n: "Confeti" },
      { e: "🎈", n: "Globo" }, { e: "🎂", n: "Torta" }, { e: "🥂", n: "Brindis" }, { e: "🍾", n: "Champán" },
      { e: "🎄", n: "Navidad" }, { e: "🎃", n: "Calabaza" }, { e: "🎆", n: "Fuegos artificiales" }, { e: "🎇", n: "Bengala" },
      { e: "🪅", n: "Piñata" }, { e: "💌", n: "Carta de amor" }, { e: "🏆", n: "Trofeo" }, { e: "🥇", n: "Medalla de oro" },
      { e: "🎵", n: "Nota musical" }, { e: "🎤", n: "Micrófono" }, { e: "🪩", n: "Bola disco" },
    ],
  },
  {
    id: "deportes",
    nombre: "Deportes",
    icono: "⚽",
    conTono: false,
    emojis: [
      { e: "⚽", n: "Fútbol" }, { e: "🏀", n: "Baloncesto" }, { e: "🏈", n: "Fútbol americano" }, { e: "⚾", n: "Béisbol" },
      { e: "🎾", n: "Tenis" }, { e: "🏐", n: "Voleibol" }, { e: "🏓", n: "Ping pong" }, { e: "🥊", n: "Boxeo" },
      { e: "🏋️‍♀️", n: "Pesas" }, { e: "🚴‍♀️", n: "Ciclismo" }, { e: "🏊‍♀️", n: "Natación" }, { e: "🧘‍♀️", n: "Yoga" },
      { e: "🎯", n: "Diana" }, { e: "🎮", n: "Videojuegos" }, { e: "🎲", n: "Dados" }, { e: "♟️", n: "Ajedrez" },
      { e: "🏅", n: "Medalla" }, { e: "🥋", n: "Artes marciales" },
    ],
  },
  {
    id: "viajes",
    nombre: "Viajes y lugares",
    icono: "✈️",
    conTono: false,
    emojis: [
      { e: "✈️", n: "Avión" }, { e: "🚗", n: "Carro" }, { e: "🛵", n: "Motoneta" }, { e: "🏍️", n: "Moto" },
      { e: "🚌", n: "Guagua" }, { e: "🚲", n: "Bicicleta" }, { e: "⛵", n: "Velero" }, { e: "🚢", n: "Barco" },
      { e: "🏖️", n: "Playa" }, { e: "🏝️", n: "Isla" }, { e: "🏠", n: "Casa" }, { e: "🏪", n: "Tienda" },
      { e: "🏬", n: "Centro comercial" }, { e: "🏨", n: "Hotel" }, { e: "🗺️", n: "Mapa" }, { e: "🧳", n: "Maleta" },
      { e: "📍", n: "Ubicación" }, { e: "🌆", n: "Ciudad" }, { e: "🚀", n: "Cohete" }, { e: "🎡", n: "Rueda de la fortuna" },
    ],
  },
  {
    id: "objetos",
    nombre: "Objetos y hogar",
    icono: "🛋️",
    conTono: false,
    emojis: [
      { e: "📱", n: "Celular" }, { e: "💻", n: "Laptop" }, { e: "📷", n: "Cámara" }, { e: "🎧", n: "Audífonos" },
      { e: "💡", n: "Bombillo" }, { e: "🔑", n: "Llave" }, { e: "🛋️", n: "Sofá" }, { e: "🛏️", n: "Cama" },
      { e: "🪑", n: "Silla" }, { e: "🚿", n: "Ducha" }, { e: "🧺", n: "Canasta" }, { e: "🖼️", n: "Cuadro" },
      { e: "🪴", n: "Matera" }, { e: "🧹", n: "Escoba" }, { e: "🛒", n: "Carrito" }, { e: "🛍️", n: "Bolsas de compras" },
      { e: "📦", n: "Paquete" }, { e: "🏷️", n: "Etiqueta" }, { e: "💰", n: "Bolsa de dinero" }, { e: "💵", n: "Billete" },
      { e: "💳", n: "Tarjeta" }, { e: "🧾", n: "Recibo" }, { e: "📞", n: "Teléfono" }, { e: "📅", n: "Calendario" },
      { e: "✏️", n: "Lápiz" }, { e: "📚", n: "Libros" }, { e: "🎨", n: "Paleta" }, { e: "🪡", n: "Aguja" },
      { e: "🧵", n: "Hilo" }, { e: "🧶", n: "Lana" }, { e: "🔔", n: "Campana" }, { e: "⌚", n: "Reloj" },
      { e: "⏰", n: "Despertador" }, { e: "🧸", n: "Peluche" }, { e: "🪆", n: "Muñeca rusa" }, { e: "🔦", n: "Linterna" },
    ],
  },
  {
    id: "banderas",
    nombre: "Banderas",
    icono: "🇩🇴",
    conTono: false,
    emojis: [
      { e: "🇩🇴", n: "República Dominicana" }, { e: "🇺🇸", n: "Estados Unidos" }, { e: "🇵🇷", n: "Puerto Rico" }, { e: "🇨🇺", n: "Cuba" },
      { e: "🇻🇪", n: "Venezuela" }, { e: "🇨🇴", n: "Colombia" }, { e: "🇲🇽", n: "México" }, { e: "🇪🇸", n: "España" },
      { e: "🇭🇹", n: "Haití" }, { e: "🇧🇷", n: "Brasil" }, { e: "🇦🇷", n: "Argentina" }, { e: "🇮🇹", n: "Italia" },
      { e: "🇫🇷", n: "Francia" }, { e: "🇨🇦", n: "Canadá" }, { e: "🏳️‍🌈", n: "Arcoíris" }, { e: "🏁", n: "Meta" },
      { e: "🚩", n: "Bandera roja" }, { e: "🏳️", n: "Bandera blanca" },
    ],
  },
];
